### ISSUE TITLE
Add tags for RR 140, 219, 232, 282, 355, 356, 368, 371, 376, and 388

### ISSUE THREAD

**Issue by andrewmcodes** [cmaxw/devchat-eleventy#5]
I will be adding tags for the following ruby rogues episodes in an accompanying pr (#7):

- [x] 140
- [x] 219
- [x] 232
- [x] 282
- [x] 355
- [x] 356
- [x] 368
- [x] 371
- [x] 376
- [x] 388

**Comment by cmaxw** [comment]
Thanks Andrew for the taggings.
