### ISSUE TITLE
RSS Feeds not working

### ISSUE THREAD

**Issue by MRR0GERS** [cmaxw/devchat-eleventy#69]
I tried subscribing to some shows from my podcast app and they weren't working.  I went to get the RSS feeds directly and it looks like the feeds are broken.
![Screenshot_20191113-090125](https://user-images.githubusercontent.com/33129628/68770504-440bbb00-05f4-11ea-9bd2-85d388dbaa15.jpg)

**Comment by cmaxw** [comment]
I got this back up. That RSS feed URL is incorrect too, so I'll push a fix. https://feeds.feedwrench.com/dev-ed.rss

**Comment by paulayo93** [comment]
> I got this back up. That RSS feed URL is incorrect too, so I'll push a fix. https://feeds.feedwrench.com/dev-ed.rss

Hello @cmaxw I am trying to listen to the podcast from VLC Player via the rss feed, but it not working.
Please, How do I solve this issue?
Thanks

![Annotation 2020-08-21 062222](https://user-images.githubusercontent.com/52790286/90855165-d062bf80-e376-11ea-8f94-4d9306e7bfc0.png)
